services:
  - type: web
    name: byte-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: MYSQL_ADDON_HOST
        sync: false
      - key: MYSQL_ADDON_DB
        sync: false
      - key: MYSQL_ADDON_USER
        sync: false
      - key: MYSQL_ADDON_PASSWORD
        sync: false
      - key: MYSQL_ADDON_PORT
        value: "3306"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: AWS_REGION
        value: "eu-north-1"
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
